version: "3.9"
services:
    player:
        build: player/
        container_name: player
        ports:
            - 8090:8090
        networks:
            blocknet:
    blockchain:
        build: blockchain_service/
        container_name: blockchain
        ports:
            - 8091:8091
        networks:
            blocknet:
networks:
    blocknet:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.0.0.0/16
                  gateway: 172.0.0.1